spring:
  profiles: common

tencent:
  cloud:
    appId: 微信小程序Appid
    secretId: 腾讯云ID
    secretKey: 密钥
    region-public: 存储同位置
    bucket-public: 存储桶名字
    region-private: 存储桶位置
    bucket-private: 存储桶名字
    face:
      groupName: hxds
      region: ap-beijing
  map:
    key: 腾讯位置服务密钥

wx:
  app-id: 微信小程序APPID
  app-secret: 小程序密钥
  mch-id: 商户号
  key: 商户密钥
  cert-path: F:\apiclient_cert.p12

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: 密码

